services:
  - type: web
    name: solith-backend
    env: node
    buildCommand: npm install --prefix server
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
      - key: ALLOWED_ORIGIN
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false
